name: hello

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    branches:
      - 'main'
jobs:
  job1_echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with pylint
      run: |
        #pylint $(git ls-files '*.py')
        echo "Hello"
